# Generated by Django 4.0.1 on 2022-01-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
    ]
