# Generated by Django 4.0.1 on 2022-01-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0003_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('marks', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
