# Generated by Django 4.0.1 on 2022-01-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0004_student2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student2',
            table='Student2',
        ),
    ]
