# Generated by Django 4.0.1 on 2022-01-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0005_alter_student2_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student2',
        ),
    ]
