# Generated by Django 4.0.1 on 2022-01-27 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0006_delete_student2'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'College',
            },
        ),
        migrations.AlterModelTable(
            name='student',
            table='Stud',
        ),
        migrations.CreateModel(
            name='Princi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='First_app.college')),
            ],
            options={
                'db_table': 'princi',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intake', models.IntegerField(default=60)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='First_app.college')),
            ],
            options={
                'db_table': 'depart',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='First_app.department'),
        ),
    ]
