# Generated by Django 4.0.1 on 2022-01-31 12:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0007_college_alter_student_table_princi_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='college',
        ),
        migrations.RemoveField(
            model_name='princi',
            name='college',
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('person', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Princi',
        ),
    ]
